name: CI/CD

on: [push, pull_request]

jobs:
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86
      
      - name: Build
        run: msbuild projects/vs2019/projects.sln -t:rebuild -property:Configuration=Release -maxcpucount:2
      
      - name: Deploy
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Win32
          path: |
            projects/vs2019/Release/hl_cdll/client.dll
            projects/vs2019/Release/hl_cdll/client.pdb
            projects/vs2019/Release/hldll/hl.dll
            projects/vs2019/Release/hldll/hl.pdb
      
